<html>

<head>
    <title>Secure Login</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>

<body>
    <div class="">
        <div class="panel panel-login">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-6">
                        <a href="../login" class="active" id="login-form-link">Login</a>
                    </div>
                    <div class="col-xs-6">
                        <a href="../register" id="register-form-link">Register</a>
                    </div>
                    <div class="col-xs-6">
                        <a href="logout" id="register-form-link">Logout</a>
                    </div>
                </div>
                <hr>
            </div>
        </div>
